BOT_TOKEN = "7044072536:AAHFKOGa9m3VE5RbiKiTMICbzU897LVrt7I"
DB_NAME = "data.db"

START_COMMAND_DESCRIPTION = "🤖 Botni ishga tushurish"
SIGN_UP_TEXT = "👤 Ro'yxatdan o'tish"
SEND_PHONE_NUMBER_TEXT = '📞 Telefon raqamni yuborish'
START_TEXT = "🤖 Assalomu alaykum. Botdan foydalanish uchun ro'yxatdan o'tishingiz kerak."
WELCOME_TEXT = "🤖 Assalomu alaykum  {}!"
SIGNED_UP_TEXT = "🤖 Hurmatli {}, siz ro'yxatdan o'tgansiz"
ENTER_NAME_TEXT = "✍️ Iltimos ismingizni kiriting"
ENTER_PHONE_NUMBER_TEXT = "📞 Iltimos telefon raqamingizni yuboring"
ENTER_ADDRESS_TEXT = "🏠 Yashash manzilingiz:"
ENTER_PROMO_PHOTO_TEXT = "🖼 Kupon rasmini yuboring:"
ENTER_PHOTO_TEXT = "🖼 Rasm ko'rinishida yuboring"
PHOTO_SAVED_TEXT = "🖼 Rasm saqlandi"
ENTER_PROMO_CODE_TEXT = "🎟 Promo kodni kiriting"
DATA_SAVED_TEXT = "✅ Ma'lumotlar saqlandi"
INFO_TEXT = ("<b>👤 Ism:</b>  {}\n"
             "<b>📞 Telefon raqam:</b>  {}\n"
             "<b>🏠 Yashash manzil:</b>  {}\n"
             "<b>🎟 Promo kod:</b>  {}")
